AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to control smart-garage using Alexa Smart Home skill

Resources:
  SmartGarageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda to control smart-garage using Alexa Smart Home skill
      CodeUri: .
      Handler: src/app.handler
      Runtime: nodejs10.x
      Tracing: Active
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSIoTFullAccess
      Environment:
        Variables:
          AWS_SERVICE_REGION: us-east-1
          DDB_TABLE_NAME: !Ref DDBTable
          IOT_ENDPOINT: xxx.iot.us-east-1.amazonaws.com
          IOT_TOPIC_PREFIX: smart-garage
          # TODO: support multiple garage, clients
          IOT_CLIENT_ID: lotus-garage-raspi-w

      # TODO: https://github.com/awslabs/serverless-application-model/pull/363
      # Events:
      #   AlexaSkillEvent:
      #     Type: AlexaSkill

  DDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

Outputs:
  LambdaFunction:
    Description: "Lambda function ARN"
    Value: !GetAtt SmartGarageFunction.Arn
